### ISSUE TITLE
Global

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.ja-jp#11]
English:
Create DAX Calculations in Power BI Desktop, Part 1

Current Translation:
Power BI Desktop での DAX 計算の作成、パート 1

Suggested Translation:
Power BI Desktop で DAX 計算を作成する (パート 1)

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by olprod** [comment]
https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.ja-jp/blob/OLPRODLOC/Instructions/10-row-level-security.md
https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.ja-jp/blob/OLPRODLOC/Instructions/05-create-dax-calculations-in-power-bi-desktop-advanced.md
https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.ja-jp/blob/OLPRODLOC/Instructions/04-create-dax-calculations-in-power-bi-desktop.md

**Comment by stonezy123** [comment]
Run bugfix tool and waiting for result.[ ICMS QUERY](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=C%26E&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPlRydWU8L0lEPjxFTEM%2bRmFsc2U8L0VMQz48QU1QPkZhbHNlPC9BTVA%2bPFNPSFJJUj5GYWxzZTwvU09IUklSPjxTSFJQPkZhbHNlPC9TSFJQPjxTQVRPPkZhbHNlPC9TQVRPPjxTQUxPPlRydWU8L1NBTE8%2bPFFFPj4yPC9RRT48UVQ%2bPjxRUiBJZD0iMSIgQ1BJRD0iMCI%2bQ3VycmVudDtGaWxlcztIb3N0IENvbnRlbnQgU3RvcmU7RXF1YWw7TEFCX1BMLTMwMFQwMDwvUVI%2bPFFSIElkPSIyIiBDUElEPSIwIj5hbmQ7Q3VycmVudDtMb2NGaWxlcztMYW5ndWFnZTtFcXVhbDtKYXBhbmVzZSAoSmFwYW4pPC9RUj48UVIgSWQ9IjMiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0ZpbGVzO0hvc3QgQXNzZXQgSUQ7SXMgSW4gTGlzdDsxMC1yb3ctbGV2ZWwtc2VjdXJpdHkubWQueGxmLDA1LWNyZWF0ZS1kYXgtY2FsY3VsYXRpb25zLWluLXBvd2VyLWJpLWRlc2t0b3AtYWR2YW5jZWQubWQueGxmLDA0LWNyZWF0ZS1kYXgtY2FsY3VsYXRpb25zLWluLXBvd2VyLWJpLWRlc2t0b3AubWQueGxmPC9RUj48L1FUPjxSRz48R0M%2bTlVMTDwvR0M%2bPC9SRz48L1ZQUT4%3d)

**Comment by olprod** [comment]
![image](https://user-images.githubusercontent.com/16075726/185302552-c10cdbdb-470d-4ed0-8789-7041ddae05bd.png)
