### ISSUE TITLE
03-configure-data-model-in-power-bi-desktop.md(Global) 04-create-dax-calculations-in-power-bi-desktop.md(Global)

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.ja-jp#15]
English:
'Model Data in Power BI Desktop, Part 2
lab,

Current Translation:
「
Power BI Desktop でのデータのモデル化 (パート 2)
」ラボ

Suggested Translation:
「
Power BI Desktop でデータをモデル化する (パート 2)
」ラボ

**Comment by stonezy123** [comment]
No locfile in iCMS, So I Re-index the file, waiting for result. [ICMS QUERY](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=C%26E&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5GYWxzZTwvU0hSUD48U0FUTz5GYWxzZTwvU0FUTz48U0FMTz5UcnVlPC9TQUxPPjxRRT4%2bMTwvUUU%2bPFFUPj48UVIgSWQ9IjEiIENQSUQ9IjAiPkN1cnJlbnQ7RmlsZXM7SG9zdCBDb250ZW50IFN0b3JlO0VxdWFsO0xBQl9QTC0zMDBUMDA8L1FSPjxRUiBJZD0iMiIgQ1BJRD0iMCI%2bYW5kO0N1cnJlbnQ7RmlsZXM7SG9zdCBBc3NldCBJRDtDb250YWluczswMy1jb25maWd1cmUtZGF0YS1tb2RlbC1pbi1wb3dlci1iaS1kZXNrdG9wLm1kPC9RUj48L1FUPjxSRz48R0M%2bTlVMTDwvR0M%2bPC9SRz48L1ZQUT4%3d)  AND [ICMS QUERY](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=C%26E&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5GYWxzZTwvU0hSUD48U0FUTz5GYWxzZTwvU0FUTz48U0FMTz5UcnVlPC9TQUxPPjxRRT4%2bMTwvUUU%2bPFFUPj48UVIgSWQ9IjEiIENQSUQ9IjAiPkN1cnJlbnQ7RmlsZXM7SG9zdCBDb250ZW50IFN0b3JlO0VxdWFsO0xBQl9QTC0zMDBUMDA8L1FSPjxRUiBJZD0iMiIgQ1BJRD0iMCI%2bYW5kO0N1cnJlbnQ7RmlsZXM7SG9zdCBBc3NldCBJRDtDb250YWluczswNC1jcmVhdGUtZGF4LWNhbGN1bGF0aW9ucy1pbi1wb3dlci1iaS1kZXNrdG9wLm1kLnhsZjwvUVI%2bPC9RVD48Ukc%2bPEdDPk5VTEw8L0dDPjwvUkc%2bPC9WUFE%2b)

**Comment by stonezy123** [comment]
locfile in Loclization status. [icms query](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=C%26E&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5GYWxzZTwvU0hSUD48U0FUTz5GYWxzZTwvU0FUTz48U0FMTz5UcnVlPC9TQUxPPjxRRT4%2bMjwvUUU%2bPFFUPj48UVIgSWQ9IjEiIENQSUQ9IjAiPkN1cnJlbnQ7RmlsZXM7SG9zdCBDb250ZW50IFN0b3JlO0VxdWFsO0xBQl9QTC0zMDBUMDA8L1FSPjxRUiBJZD0iMiIgQ1BJRD0iMCI%2bYW5kO0N1cnJlbnQ7RmlsZXM7SG9zdCBGaWxlIFJlZmVyZW5jZTtFcXVhbDtodHRwczovL2dpdGh1Yi5jb20vTWljcm9zb2Z0TGVhcm5pbmcvUEwtMzAwLU1pY3Jvc29mdC1Qb3dlci1CSS1EYXRhLUFuYWx5c3QvYmxvYi9NYWluL0luc3RydWN0aW9ucy8wNC1jcmVhdGUtZGF4LWNhbGN1bGF0aW9ucy1pbi1wb3dlci1iaS1kZXNrdG9wLm1kPC9RUj48L1FUPjxSRz48R0M%2bTlVMTDwvR0M%2bPC9SRz48L1ZQUT4%3d)

**Comment by stonezy123** [comment]
Can't find the Current Translation

**Comment by olprod** [comment]
Can't find
