### ISSUE TITLE
Global

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.ja-jp#20]
English:
Stop Viewing

Current Translation:
表示を中止

Suggested Translation:
表示を停止

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
Now, the locfile shown : 
![image](https://user-images.githubusercontent.com/49666210/177716929-0434d703-009b-4cbf-ac2f-f4870fbd7d84.png)
