### ISSUE TITLE
Image don't display 

### ISSUE THREAD

**Issue by saleoq** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.ja-jp#21]
Cannot see image in all JP instruction.
![Not show](https://user-images.githubusercontent.com/105509625/168325309-1a8bda48-c622-4eea-81d8-466ff85825e0.jpg)
.

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
Because the locrepo don't have this image, so show the content. this is by-designed,
but if this locrepo publish, will shown the source image, don't fix it.

**Comment by stonezy123** [comment]
The locfile image shown inloclization status, waiting for check In. [ICMS QUERY](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=C%26E&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5GYWxzZTwvU0hSUD48U0FUTz5GYWxzZTwvU0FUTz48U0FMTz5UcnVlPC9TQUxPPjxRRT4%2bMjwvUUU%2bPFFUPj48UVIgSWQ9IjEiIENQSUQ9IjAiPkN1cnJlbnQ7RmlsZXM7SG9zdCBDb250ZW50IFN0b3JlO0VxdWFsO0xBQl9QTC0zMDBUMDA8L1FSPjxRUiBJZD0iMiIgQ1BJRD0iMCI%2bYW5kO0N1cnJlbnQ7TG9jRmlsZXM7TGFuZ3VhZ2U7RXF1YWw7SmFwYW5lc2UgKEphcGFuKTwvUVI%2bPFFSIElkPSIzIiBDUElEPSIwIj5hbmQ7Q3VycmVudDtGaWxlcztIb3N0IEZpbGUgUmVmZXJlbmNlO0NvbnRhaW5zO0luc3RydWN0aW9ucy9MaW5rZWRfaW1hZ2VfRmlsZXMvPC9RUj48L1FUPjxSRz48R0M%2bTlVMTDwvR0M%2bPC9SRz48L1ZQUT4%3d)

**Comment by chriscarty00** [comment]
All seem displaying now fix for https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.ja-jp/issues/26 seems to have addressed this issue
