### ISSUE TITLE
PL-300 Lab Correction Report

### ISSUE THREAD

**Issue by saleoq** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.ja-jp#26]
Please find the correction in PL-300 Lab for URL path, image etc. Thanks.

■GitHub Lab
1.読み込み時の .pbix ファイルのパス名
　修正前：D:\PL300\Labs\02-load-data-with-power-query-in-power-bi-desktop\starter
  修正後：：D:\PL300\Labs01\Starter\02-load-data-with-power-query-in-power-bi-desktop\starter
　※全ての読み込み情報修正

2.ラボ環境の Power BI Desktop バージョン違いによる古い画像
　2022年02月バージョンに取得済
　日本語環境用に取得済

3.D:\PL300\Setup\Scripts\UpdateDatabase-2.sql 修正
　読み込むファイルに誤り有り
　修正前：D:\DA100\Resources\ResellerSales_202006.csv
　修正後：D:\PL300\Resources\ResellerSales_202006.csv

4.その他
　2022年02月バージョンで項目名など修正

■GitHub
1.Power BI Desktop でのデータの準備
https://github.com/s-kawara/PL-300-Microsoft-Power-BI-Data-Analyst.ja-jp/blob/main/Instructions/01-prepare-data-with-power-query-in-power-bi-desktop.md

2.Power BI Desktop でデータを読み込む
https://github.com/s-kawara/PL-300-Microsoft-Power-BI-Data-Analyst.ja-jp/blob/main/Instructions/02-load-data-with-power-query-in-power-bi-desktop.md

3.Power BI Desktop でデータをモデル化する (パート 1)
https://github.com/s-kawara/PL-300-Microsoft-Power-BI-Data-Analyst.ja-jp/blob/main/Instructions/04-create-dax-calculations-in-power-bi-desktop.md

4.Power BI Desktop で DAX 計算を作成する (パート 1)
https://github.com/s-kawara/PL-300-Microsoft-Power-BI-Data-Analyst.ja-jp/blob/main/Instructions/04-create-dax-calculations-in-power-bi-desktop.md

5.Power BI Desktop で DAX 計算を作成する (パート 2)
https://github.com/s-kawara/PL-300-Microsoft-Power-BI-Data-Analyst.ja-jp/blob/main/Instructions/05-create-dax-calculations-in-power-bi-desktop-advanced.md

6.Power BI Desktop でレポートを設計する (パート 1)
https://github.com/s-kawara/PL-300-Microsoft-Power-BI-Data-Analyst.ja-jp/blob/main/Instructions/06-design-report-in-power-bi-desktop.md

7.Power BI Desktop でレポートを設計する (パート 2)
https://github.com/s-kawara/PL-300-Microsoft-Power-BI-Data-Analyst.ja-jp/blob/main/Instructions/07-design-report-in-power-bi-desktop-enhanced.md

8.Power BI ダッシュボードを作成する
https://github.com/s-kawara/PL-300-Microsoft-Power-BI-Data-Analyst.ja-jp/blob/main/Instructions/08-create-power-bi-dashboard.md

9.Power BI Desktop でデータ分析を実行する
https://github.com/s-kawara/PL-300-Microsoft-Power-BI-Data-Analyst.ja-jp/blob/main/Instructions/09-perform-data-analysis-in-power-bi-desktop.md

10.行レベルのセキュリティを適用する
https://github.com/s-kawara/PL-300-Microsoft-Power-BI-Data-Analyst.ja-jp/blob/main/Instructions/10-row-level-security.md

**Comment by stonezy123** [comment]
I don't know what need to fix? please help clarify

**Comment by stonezy123** [comment]
issue 1 and issue 3 The Url  same as source. Rejected.

issue 1:
https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/blob/master/Instructions/02-load-data-with-power-query-in-power-bi-desktop.md
![image](https://user-images.githubusercontent.com/49666210/185047607-af9a7475-7e2d-4107-b81b-c8a6d8b2d2de.png)

issue 3:
https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst/blob/master/Allfiles/Setup/Scripts/UpdateDatabase-2.sql
![image](https://user-images.githubusercontent.com/49666210/185048192-b6526373-ccd8-47f0-8b2b-0afefb7d1022.png)

and about the image issue, have dup issue:  https://github.com/MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.ja-jp/issues/21

so will close it.
