### ISSUE TITLE
Wrong folder name\path

### ISSUE THREAD

**Issue by dakozu** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.ja-jp#28]
/Allfiles/**_'Labs/01/Starter'_** should be   /Allfiles/**_Labs_**
![image](https://user-images.githubusercontent.com/32472054/205559963-cffd0536-4cfe-43bd-ba12-71d53b76da3a.png)

Please change the path to the same as the English version.

![image](https://user-images.githubusercontent.com/32472054/205559896-923ef2ff-4ee8-4802-ab9e-e96bcf994ea7.png)

**Comment by chriscarty00** [comment]
Same as en-us now 

![image](https://user-images.githubusercontent.com/63402128/229497898-0c49b089-467e-4456-b505-f2c21165bb0b.png)
