### ISSUE TITLE
lab file is out of date

### ISSUE THREAD

**Issue by dakozu** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.ja-jp#29]
The lab file is out of date and causes errors such as file paths.
Lab files (under the Allfiles/Lab folder) should be the same as the English version.

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
Look in sync now
