### ISSUE TITLE
Module03- Exercise4 is missing.

### ISSUE THREAD

**Issue by dakozu** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst.ja-jp#30]
/Instructions/03-configure-data-model-in-power-bi-desktop.md

Module 3 instruction is finished with Exercise 3. but Module 3 shuld has Exercise 4.
Prease sync with English version.

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
Pages are now in sync
